#!/system/bin/sh

# ==UserScript==
# @name         mkshrc
# @namespace    https://github.com/hyugogirubato/mkshrc/blob/main/mkshrc
# @version      2.4
# @description  Make an advanced shell environment for Android devices
# @author       hyugogirubato
# @match        Android
# @source       https://github.com/Zackptg5/Cross-Compiled-Binaries-Android
# ==/UserScript==


# Set environment variables based on device properties
# HOSTNAME is set to the device's serial number
export HOSTNAME=$(getprop ro.boot.serialno)
# USER and LOGNAME are set to the current user's name
export USER=$(id -u -n)
export LOGNAME=$USER
# TMPDIR is set to a common temporary directory
export TMPDIR='/data/local/tmp'


# Enhance command output with color support if available
# This block checks if color support is available and sets aliases accordingly
if ls --color=auto >/dev/null 2>&1; then
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias logcat='logcat -v color'
  alias ip='ip -c'
  alias diff='diff --color'
fi

# Define commonly used aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ipa='ip a'
alias rm='rm -rf'


# Part 1: Tools & utilities
# Function to unroot files by changing ownership and permissions
_unroot() {
  if [ -e "$1" ]; then
    chown shell:shell "$1"
    chmod 755 "$1"
  fi
}

# Create a directory for binaries if it doesn't exist
binaries="$TMPDIR/bin"
mkdir -p "$binaries"
_unroot "$binaries"

# Add binaries directory to PATH if it's not already there
if ! echo "$PATH" | grep -q "$binaries"; then
  export PATH="$PATH:$binaries"
fi

# Function to simulate 'tree' command
if ! which 'tree' >/dev/null 2>&1; then
  # Referer: https://stackoverflow.com/questions/18014779/similar-command-to-linux-tree-command-in-adb-shell
  # Source: https://github.com/kddnewton/tree
  # Issue: https://github.com/kddnewton/tree/pull/12/
  path="$binaries/tree"
  url='https://github.com/hyugogirubato/mkshrc/raw/main/tree'
  curl -fsL -o "$path" "$url" || { echo "Failed to download tree from $url" >&2; return 1; }
  _unroot "$path"
fi

# Function to simulate 'man' command
man() {
  [ -z "$1" ] && { echo -e "What manual page do you want?\nFor example, try 'man ls'." >&2; return 1; }
  "$1" --help >/dev/null 2>&1 && "$1" --help 2>&1 || { echo "No manual entry for $1" >&2; return 16; }
}

# Custom find command that displays colored results
cfind() {
  if ls --color=auto $TMPDIR >/dev/null 2>&1; then
    find "${1:-.}" -print0 | xargs -0 ls --color=auto -d1
  else
    echo 'Unsupported XTerm environment' >&2; return 1
  fi
}


# Part 2: Busybox
# Function to determine the device's architecture
_arch() {
  # Source: https://github.com/Magisk-Modules-Repo/busybox-ndk/blob/master/customize.sh#L314C1-L334C2
  local abi=$(getprop ro.product.cpu.abi)
  case $abi in
    arm64*) ARCH='arm64' ;;
    arm*) ARCH='arm' ;;
    x86_64*) ARCH='x86_64' ;;
    x86*) ARCH='x86' ;;
    mips64*) ARCH='mips64' ;;
    mips*) ARCH='mips' ;;
    *) echo "Unknown architecture: $abi" >&2; return 1 ;;
  esac
}

# Check if Busybox is available, download if not
_arch
busybox='/sbin/.magisk/busybox/busybox'
if [ ! -f "$busybox" ]; then
  busybox="$binaries/busybox"

  if [ ! -f "$busybox" ]; then
    # Source: https://github.com/Magisk-Modules-Repo/busybox-ndk
    url="https://raw.githubusercontent.com/Magisk-Modules-Repo/busybox-ndk/master/busybox-$ARCH"
    [ -f '/sys/fs/selinux/enforce' ] && url+='-selinux'
    curl -fsL -o "$busybox" "$url" || { echo "Failed to download BusyBox from $url" >&2; return 1; }
  fi
  _unroot "$busybox"
fi

# Create symbolic links for Busybox binaries
for bin in $($busybox --list | grep -vE '^man$'); do
  link_path="$binaries/$bin"
  if ! which "$bin" >/dev/null 2>&1; then
    # Create a new symlink that correctly points to just the BusyBox binary
    ln -s "$busybox" "$link_path"
  fi
done


# Part 3: Frida
# Install Frida / sudo only if current shell is root shell or su binary exist
[ ! which 'su' >/dev/null 2>&1 -a ! $(id -u) -eq 0] && return;

# Define a sudo-like function
sudo() {
  if [ "$#" -eq 0 ]; then
    echo 'Usage: sudo <command>' >&2; return 1
  elif [ "$(id -u)" -eq 0 ]; then
    # Execute the command directly if already root
    "$@"
  elif [ ! which 'su' >/dev/null 2>&1 ]; then
    echo 'su binary not found' >&2; return 127
  else
    local cmd="$@"
    local alias=$(command -v "$1")

    if echo "$alias" | grep -q "^alias "; then
      alias=$(echo "$alias" | grep -o "^alias .*$" | cut -d "'" -f2)
      cmd=$(echo "$cmd" | sed "s:$1:$alias:g")
    fi

    # Use a subshell to ensure proper handling of special characters and redirections
    su -c "$cmd"
  fi
}

# Install Frida server
frida="$binaries/frida-server"
if ! echo "$ARCH" | grep -q 'mips' && [ ! -f "$frida" ]; then
  # Source: https://github.com/frida/frida
  version='16.2.1'
  url="https://github.com/frida/frida/releases/download/$version/frida-server-$version-android-$ARCH.xz"
  curl -fsL -o "$frida.xz" "$url" || { echo "Failed to download Frida from $url" >&2; return 1; }
  xz -d "$frida.xz"
fi

[ -f "$frida" ] && _unroot "$frida"

# Function to check Frida server status
frida-status() {
  local pid=$(pgrep -f frida-server)
  [ -z "$pid" ] && echo 'Frida not running' ||  echo "Frida PID: $pid"
}

# Function to start Frida server
frida-start() {
  local pid=$(pgrep -f frida-server)
  if [ -z "$pid" ]; then
    # Set SELinux to permissive mode silently
    sudo setenforce 0 >/dev/null 2>&1
    sudo frida-server -D "$@" || { echo 'Failed to start Frida' >&2; return 1; }
  else
    echo 'Frida already running'
  fi
}

# Function to stop Frida server
frida-stop() {
  local pid=$(pgrep -f frida-server)
  if [ ! -z "$pid" ]; then
    sudo kill -9 $pid || { echo 'Failed to stop Frida' >&2; return 1; }
    sudo setenforce 1 >/dev/null 2>&1

    # Check again if Frida server is still running
    if pgrep -f frida-server &>/dev/null; then
      [ -d '/sbin/.magisk/' ] && echo 'Use Magisk to stop Frida' >&2 || echo 'Frida still running' >&2
      return 1
    fi
  fi
}