#!/system/bin/sh

# ==UserScript==
# @name         mkshrc
# @namespace    https://github.com/hyugogirubato/mkshrc
# @version      1.10
# @description  Make an advanced shell environment for Android devices
# @author       hyugogirubato
# @match        Android
# ==/UserScript==


# Set environment variables based on device properties
export HOSTNAME=$(getprop ro.boot.serialno)
export USER=$(id -u -n)
export LOGNAME=$USER
export TMPDIR=${TMPDIR:-'/data/local/tmp'}


# Find the architecture of the Android device using CPU ABI
_arch() {
  # Source: https://github.com/Magisk-Modules-Repo/busybox-ndk/blob/master/customize.sh#L314C1-L334C2
  local abi=$(getprop ro.product.cpu.abi)
  case $abi in
    arm64*) ARCH='arm64' ;;
    arm*) ARCH='arm' ;;
    x86_64*) ARCH='x86_64' ;;
    x86*) ARCH='x86' ;;
    mips64*) ARCH='mips64' ;;
    mips*) ARCH='mips' ;;
    *) echo "Unknown architecture: $abi" >&2; return 1 ;;
  esac
}


# Initialize the architecture
_arch

# Define and verify the path to the BusyBox binary
busybox='/sbin/.magisk/busybox/busybox'
if [ ! -f "$busybox" ]; then
  busybox="$TMPDIR/busybox"

  # Source: https://github.com/Magisk-Modules-Repo/busybox-ndk
  url="https://raw.githubusercontent.com/Magisk-Modules-Repo/busybox-ndk/master/busybox-$ARCH"
  [ -f '/sys/fs/selinux/enforce' ] && url+='-selinux'
  curl -fs -o "$busybox" "$url" || { echo "Failed to download BusyBox from $url" >&2; return 1; }

  # Ensure BusyBox binary is executable
  chmod 755 "$busybox"
  chown shell:shell "$busybox"
fi

# Create aliases for BusyBox commands
for bin in $($busybox --list | grep -vE '^man$'); do
  alias "$bin"="$busybox $bin" 2>/dev/null
done

# Handle Frida installation if Magisk is not installed
if [ ! -d '/sbin/.magisk/' ]; then
  frida="$TMPDIR/frida-server"

  if [ ! -f "$frida" ]; then
    # Source: https://github.com/frida/frida
    version='16.2.1'
    url="https://github.com/frida/frida/releases/download/$version/frida-server-$version-android-$ARCH.xz"
    curl -fsL -o "$frida.xz" "$url" || { echo "Failed to download Frida from $url" >&2; return 1; }
    $busybox xz -d "$frida.xz"
  fi

  # Ensure Frida binary is executable
  chmod 755 "$frida"
  chown shell:shell "$frida"
  alias 'frida-server'="$frida"
elif [ ! -d '/sbin/.magisk/modules/magisk-frida' ]; then
  echo 'Install Frida using: https://github.com/ViRb3/magisk-frida'
fi

# Enhance command output with color support if available
if ls --color=auto >/dev/null 2>&1; then
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias logcat='logcat -v color'
  alias ip='ip --color=auto'
  alias diff='diff --color=auto'
fi

# Define commonly used aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ipa='ip a'
alias rm='rm -rf'

# Display directory tree
tree() {
  # Source: https://stackoverflow.com/questions/18014779/similar-command-to-linux-tree-command-in-adb-shell
  local parent="${1:-.}"

  local files=0
  local dirs=0
  local status=0
  if [ -d "$parent" -a -r "$parent" ]; then
    # Create a temporary file
    rm -rf $TMPDIR/tmp.* 2>/dev/null
    local tempfile=$(mktemp)

    # Store sorted find results in a temporary file
    find "$parent" 2>/dev/null | sort > "$tempfile"

    # Read from the temporary file
    while IFS= read -r path; do
      if [ "$(realpath "$path" )" != "$tempfile" ]; then
        [ -f "$path" ] && ((files++))
        [ -d "$path" ] && ((dirs++))
        echo "$path" | sed 's;[^/]*/;├── ;g;s;── ├;   │;g;s;├   ;│   ;g;s;│──;├──;g'
      fi
    done < "$tempfile"

    # Remove the temporary file
    rm "$tempfile"
    ((dirs--))
  else
    echo "$parent  [error opening dir]"
    status=2
  fi

  echo -e "\n$dirs directories, $files files"
  return $status
}

# Custom find command that displays colored results
cfind() {
  if ls --color=auto $TMPDIR >/dev/null 2>&1; then
    find "${1:-.}" -print0 | xargs -0 ls -d1 --color=auto
  else
    echo 'Unsupported XTerm environment' >&2; return 1
  fi
}

_resolve() {
  local bin=$(command -v "$1")

  # Check if command starts with 'alias' using grep and extract the aliased command
  if echo "$bin" | grep -q "^alias "; then
    bin=$(echo "$bin" | grep -o "^alias .*$" | cut -d "'" -f2)
    # Remove any arguments that the alias may contain
    bin=$(echo "$bin" | cut -d '-' -f1)
  fi
  echo "$bin"
}

# Simulate 'man' command
man() {
  [ -z "$1" ] && { echo -e "What manual page do you want?\nFor example, try 'man ls'." >&2; return 1; }
  local cmd=$(_resolve "$1")
  # Check and display the help, providing a fallback message if the help cannot be displayed
  $cmd --help >/dev/null 2>&1 && $cmd --help 2>&1 | less || { echo "No manual entry for $1" >&2; return 16; }
}

# Define a sudo-like function
sudo() {
  if [ "$#" -eq 0 ]; then
    echo 'Usage: sudo <command>' >&2; return 1
  elif [ "$(id -u)" -eq 0 ]; then
    # Execute the command directly if already root
    "$@"
  elif [ -z $(_resolve 'su') ]; then
    echo 'su binary not found' >&2; return 127
  else
    # Recreate the full command string for proper shell execution
    local full_cmd="$@"

    # Construct the command to handle aliases and resolve the executable path
    local bin=$(_resolve "$1")
    if [ ! -z "$bin" ]; then
      # Replace the original command with the resolved path
      full_cmd=$(echo "$full_cmd" | sed "s:$1:$bin:g")
    fi

    # Use a subshell to ensure proper handling of special characters and redirections
    su -c "sh -c '$full_cmd'"
  fi
}

# Stop frida-server if it's running without Magisk
frida-stop() {
  if [ -d '/sbin/.magisk/' ]; then
    echo 'Use Magisk to stop Frida' >&2; return 1
  else
    local pid=$(pgrep -f frida-server)
    if [ ! -z "$pid" ]; then
      sudo kill -9 $pid || { echo 'Failed to stop Frida' >&2; return 1; }
    fi
  fi
}

# Check the status of the frida-server
frida-status() {
  local pid=$(pgrep -f frida-server)
  [ -z "$pid" ] && echo 'Frida not running' ||  echo "Frida PID: $pid"
}

# Start frida-server if it's not already running and Magisk is not installed
frida-start() {
  local pid=$(pgrep -f frida-server)
  if [ -z "$pid" ]; then
    if [ -d '/sbin/.magisk/' ]; then
      echo 'Use Magisk to start Frida' >&2; return 1
    else
      sudo setenforce 0 >/dev/null 2>&1
      sudo frida-server -D "$@" || { echo 'Failed to start Frida' >&2; return 1; }
    fi
  else
    echo 'Frida already running'
  fi
}